version: "2"

services:

  app:
    # Build application using Dockerfile contained in application subfolder
    build: ./application
    # Name image
    image: ethercis-app
    # Map application container port 8080 to Docker port 8080
    labels:
      com.microsoft.acs.dcos.marathon.healthcheck: "true"
    ports:
      - "8080:8080"
    # Do not start application container until postgres service is started
    depends_on:
      - postgres

  postgres:
    # Build database using Dockerfile contained in postgres subfolder
    build: ./postgres
    labels:
      com.microsoft.acs.dcos.marathon.healthcheck: "true"
    # Name image
    image: ethercis-db
    #Volume for postreSQL data
    volumes:
      - data:/var/lib/postgresql/data
    #Environment variables configuring Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ethercis
    ports:
      - "5432:5432"
    
